### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by xavan83** [jgow/org.openhab.binding.mqtt.frigatesvr#5]
Hello, I try to install your binding.
I found an error in the log after copying the generated jar:

2023-12-22 12:39:29.760 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/openhab/addons/org.openhab.binding.mqtt.frigatesvr-4.1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mqtt.frigatesvr [300]
  Unresolved requirement: Import-Package: com.google.gson; version="[2.10.0,3.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) ~[?:?]

**Comment by jgow** [comment]
Looks like a dependency issue. I will check. In the meantime the binding will build and run successfully against openHAB 4.0.4.

**Comment by jgow** [comment]
I have not been able to repeat this issue - will close for now as it looks like a configuration problem on the host side.
