### ISSUE TITLE
Trouble installing in openHAB 4.2.0 docker container

### ISSUE THREAD

**Issue by neutmute** [jgow/org.openhab.binding.mqtt.frigatesvr#7]
Thank you for the binding. Have just installed Frigate and it is awesome.

I am having problems installing it into `openHAB 4.2.0` running as a docker container.

I have another custom add-on which is installed fine. Any clues of where to look? Logs don't show anything.

**Comment by neutmute** [comment]
Thank you - unfortunately even with the 4.2 build it silently doesn't load the frigate JAR while the other Australian BOM JAR loads up ok.

There is a possibly(?) related error when the container starts - but this appears regardless of whether the frigate JAR file is present or not

```
2024-08-08 08:07:19.869 [WARN ] [org.apache.felix.fileinstall        ] - /usr/share/openhab/addons does not exist, please create it.

2024-08-08 08:07:19.891 [ERROR] [org.apache.felix.fileinstall        ] - Cannot create folder /var/lib/openhab/tmp/bundles. Is the folder write-protected?

2024-08-08 08:07:19.894 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedServiceFactory, id=50, bundle=18/mvn:org.apache.felix/org.apache.felix.fileinstall/3.7.4]: Unexpected problem updating configuration org.apache.felix.fileinstall.f4af7866-7070-4fb3-aeb1-c2ead9ec8d43

java.lang.RuntimeException: Cannot create folder: /var/lib/openhab/tmp/bundles

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.prepareDir(DirectoryWatcher.java:647) ~[?:?]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.prepareTempDir(DirectoryWatcher.java:627) ~[?:?]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.<init>(DirectoryWatcher.java:179) ~[?:?]

	at org.apache.felix.fileinstall.internal.FileInstall.updated(FileInstall.java:250) ~[?:?]

	at org.apache.felix.fileinstall.internal.FileInstall$ConfigAdminSupport$Tracker.updated(FileInstall.java:380) ~[?:?]

	at org.apache.felix.cm.impl.helper.ManagedServiceFactoryTracker.updated(ManagedServiceFactoryTracker.java:159) ~[bundleFile:?]

	at org.apache.felix.cm.impl.helper.ManagedServiceFactoryTracker.provideConfiguration(ManagedServiceFactoryTracker.java:93) [bundleFile:?]

	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceFactoryUpdate.provide(ConfigurationManager.java:1266) [bundleFile:?]

	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceFactoryUpdate.run(ConfigurationManager.java:1210) [bundleFile:?]

	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:122) [bundleFile:?]

	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:84) [bundleFile:?]

	at java.lang.Thread.run(Thread.java:840) [?:?]

2024-08-08 08:07:30.827 [INFO ] [org.openhab.core.Activator          ] - Starting openHAB 4.2.0 (Release Build)
```

I tried creating those missing folders in the container and restarting but to no effect other than silencing this startup error.

I'll try turning on DEBUG logging in OpenHAB and see if anything else turns up

**Comment by jgow** [comment]
I really don't know much about docker, but it would seem that for some reason your OH instance isn't either finding or seeing the .jar.

In a native install, one would simply place the .jar in /usr/share/openhab/addons and the OH instance would pick it up on load. The fact that you have had to add the /usr/share/openhab/addons folder (and I assume from your message that the frigatesvr .jar isn't in there) suggests that the OH instance isn't finding the frigatesvr jar; but then I don't know if within the docker container the OH instance is configured to look elsewhere for addons.

If there was a problem with the binding I would have expected the frigatesvr jar to load with an error, rather than silently fail to load at all.

**Comment by neutmute** [comment]
Agree - I think its my environment until proven otherwise. Thanks for the 4.2 build.
I'll do some more work my side to fault find.

**Comment by neutmute** [comment]
I've done some more digging the binding is installed, I've just been configuring the `thing` incorrectly.

I currently have an MQTT binding like this

```
Bridge mqtt:broker:PiMqttBroker [ host="192.168.20.5", secure=false, username="openhabian", password="mypassword"] {

  Thing topic garage "Garage" @ "Sonoff" {   
    Channels:
      Type switch : PushButton "Button" [stateTopic="stat/garage/POWER" , commandTopic="cmnd/garage/POWER", transformationPattern = "MAP:garage.map"]
      Type string : Sensor     "Sensor" [stateTopic="tele/garage/SENSOR", transformationPattern="JSONPATH:$.Switch2"]
  }

  Thing frigateServer frigate "frigate" 
  [ 
      serverURL="192.168.20.105:"
  ] 
}
```

Is this right? If Frigate is hosted on port 5000 should serverURL also include that?
I couldn't work out how to add the binding via UI - all my bindings are done via file.

The logs from above are like

```
2024-08-20 18:16:59.112 [INFO ] [nal.handlers.frigateSVRServerHandler] -  - Frigate server is offline
2024-08-20 18:16:59.113 [ERROR] [nternal.helpers.frigateSVRHTTPHelper] - HTTP helper called in unconfigured state
```

Frigate is up and running though. No clientID is in frigate config.yml

**Comment by neutmute** [comment]
Worked it out. URL should be a url and not hostname. duh.

**Comment by neutmute** [comment]
Happy to submit an example working config PR when I get it all going if you will accept?

**Comment by jgow** [comment]
> Happy to submit an example working config PR when I get it all going if you will accept?

Absolutely! It would certainly be helpful for those who don't use the GUI.
